### ISSUE TITLE
Example is wrong?

### ISSUE THREAD

**Issue by fbstj** [mitghi/lfqueue#1]
It seems the consumer method doesn't return anything.

**Comment by mitghi** [comment]
No it doesn't return. In this implementation, you can use Value struct:

    typedef struct _value Value;
    struct _value{
       unsigned int type;
       void *data;
    };

You can change the type to something which indicates job is processed and set the data pointer accordingly. Then in the main thread ( or other threads ), atomically check the type, if it is flagged as processed, you can get the value.

**Comment by fbstj** [comment]
But the return type is `void *` ?

**Comment by mitghi** [comment]
Its because POSIX pthread_create has following signature:

     int pthread_create(pthread_t *restrict thread,
	          const pthread_attr_t *restrict attr,
	          void *(*start_routine)(void*), void *restrict arg);

**Comment by fbstj** [comment]
ahhh ok, apologies for the uninformed questions
