### ISSUE TITLE
Valgrind reporting much memory leaks

### ISSUE THREAD

**Issue by pradeepgoswami90** [mitghi/lfqueue#7]
test 8., 100771584
==4770== Thread 2:
==4770== Invalid read of size 8
==4770==    at 0x400F71: qpop (lfq.c:126)
==4770==    by 0x400A9E: consumer (test.c:47)
==4770==    by 0x4E3F181: start_thread (pthread_create.c:312)
==4770==    by 0x514F47C: clone (clone.S:111)
==4770==  Address 0x541a040 is 0 bytes inside a block of size 16 free'd
==4770==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4770==    by 0x40121D: queue_free (lfq.c:187)
==4770==    by 0x400CE5: main (test.c:98)
==4770== 
==4770== Invalid read of size 8
==4770==    at 0x400F7C: qpop (lfq.c:127)
==4770==    by 0x400A9E: consumer (test.c:47)
==4770==    by 0x4E3F181: start_thread (pthread_create.c:312)
==4770==    by 0x514F47C: clone (clone.S:111)
==4770==  Address 0x541a048 is 8 bytes inside a block of size 16 free'd
==4770==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4770==    by 0x40121D: queue_free (lfq.c:187)
==4770==    by 0x400CE5: main (test.c:98)
==4770== 
==4770== 
==4770== HEAP SUMMARY:
==4770==     in use at exit: 784 bytes in 16 blocks
==4770==   total heap usage: 312 allocs, 296 frees, 11,888 bytes allocated
==4770== 
==4770== Thread 1:
==4770== 80 (16 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 5 of 6
==4770==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4770==    by 0x400D60: q_initialize (lfq.c:54)
==4770==    by 0x400B48: main (test.c:67)
==4770== 
==4770== 704 bytes in 11 blocks are definitely lost in loss record 6 of 6
==4770==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4770==    by 0x400BD7: main (test.c:79)
==4770== 
==4770== LEAK SUMMARY:
==4770==    definitely lost: 720 bytes in 12 blocks
==4770==    indirectly lost: 64 bytes in 4 blocks
==4770==      possibly lost: 0 bytes in 0 blocks
==4770==    still reachable: 0 bytes in 0 blocks
==4770==         suppressed: 0 bytes in 0 blocks
==4770== 
==4770== For counts of detected and suppressed errors, rerun with: -v
==4770== ERROR SUMMARY: 6 errors from 4 contexts (suppressed: 0 from 0)

**Comment by mitghi** [comment]
Oh right. I merged your pull request.

**Comment by tekknolagi** [comment]
Is this fixed?

**Comment by pradeepgoswami90** [comment]
This seems to be fixed , I have tested , below is valgrind report
@mitghi  again thanks

 test 8., 100771584
==6313== Thread 2:
==6313== Invalid read of size 8
==6313==    at 0x400F71: qpop (lfq.c:126)
==6313==    by 0x400A9E: consumer (test.c:47)
==6313==    by 0x4E3F181: start_thread (pthread_create.c:312)
==6313==    by 0x514F47C: clone (clone.S:111)
==6313==  Address 0x541a040 is 0 bytes inside a block of size 16 free'd
==6313==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==6313==    by 0x40126A: queue_free (lfq.c:193)
==6313==    by 0x400CE5: main (test.c:98)
==6313== 
==6313== Invalid read of size 8
==6313==    at 0x400F7C: qpop (lfq.c:127)
==6313==    by 0x400A9E: consumer (test.c:47)
==6313==    by 0x4E3F181: start_thread (pthread_create.c:312)
==6313==    by 0x514F47C: clone (clone.S:111)
==6313==  Address 0x541a048 is 8 bytes inside a block of size 16 free'd
==6313==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==6313==    by 0x40126A: queue_free (lfq.c:193)
==6313==    by 0x400CE5: main (test.c:98)
==6313== 
==6313== 
==6313== HEAP SUMMARY:
==6313==     in use at exit: 0 bytes in 0 blocks
==6313==   total heap usage: 312 allocs, 312 frees, 11,888 bytes allocated
==6313== 
==6313== All heap blocks were freed -- no leaks are possible
==6313== 
==6313== For counts of detected and suppressed errors, rerun with: -v
==6313== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)

**Comment by mitghi** [comment]
@tekknolagi  Yes, it is fixed.
@pradeepgoswami90 You are welcome.
